// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LowLevelCall$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LowLevelCall",
  "sourceName": "@openzeppelin/contracts/utils/LowLevelCall.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122051a0e6c47b229232680c36086a76a5b4177f261b413f6c79c12ca9b3adb055ac64736f6c634300081c0033",
  "deployedBytecode": "0x5f80fdfea264697066735822122051a0e6c47b229232680c36086a76a5b4177f261b413f6c79c12ca9b3adb055ac64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
}
