// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TrustToken$Type } from "./TrustToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TrustToken"]: TrustToken$Type;
    ["contracts/TrustToken.sol:TrustToken"]: TrustToken$Type;
  }

  interface ContractTypesMap {
    ["TrustToken"]: GetContractReturnType<TrustToken$Type["abi"]>;
    ["contracts/TrustToken.sol:TrustToken"]: GetContractReturnType<TrustToken$Type["abi"]>;
  }
}
