// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPhygitalEscrow$Type } from "./IPhygitalEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPhygitalEscrow"]: IPhygitalEscrow$Type;
    ["contracts/interfaces/IPhygitalEscrow.sol:IPhygitalEscrow"]: IPhygitalEscrow$Type;
  }

  interface ContractTypesMap {
    ["IPhygitalEscrow"]: GetContractReturnType<IPhygitalEscrow$Type["abi"]>;
    ["contracts/interfaces/IPhygitalEscrow.sol:IPhygitalEscrow"]: GetContractReturnType<IPhygitalEscrow$Type["abi"]>;
  }
}
