// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IPhygitalEscrow$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IPhygitalEscrow",
  "sourceName": "contracts/interfaces/IPhygitalEscrow.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "price",
          "type": "uint256"
        }
      ],
      "name": "calcCollateral",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "tokenId",
          "type": "uint256"
        },
        {
          "internalType": "address payable",
          "name": "seller",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "price",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "redeemStart",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "redeemEnd",
          "type": "uint256"
        }
      ],
      "name": "createListing",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "listingId",
          "type": "uint256"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "listingId",
          "type": "uint256"
        },
        {
          "internalType": "bool",
          "name": "buyerWins",
          "type": "bool"
        }
      ],
      "name": "executeVerdict",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "seller",
          "type": "address"
        },
        {
          "internalType": "string",
          "name": "pubkey",
          "type": "string"
        }
      ],
      "name": "setSellerPubkeyByCollection",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IPhygitalEscrow",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPhygitalEscrow$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/IPhygitalEscrow.sol:IPhygitalEscrow",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPhygitalEscrow$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IPhygitalEscrow",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPhygitalEscrow$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/IPhygitalEscrow.sol:IPhygitalEscrow",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPhygitalEscrow$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IPhygitalEscrow",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPhygitalEscrow$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/IPhygitalEscrow.sol:IPhygitalEscrow",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPhygitalEscrow$Type["abi"]>>;
}
