// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1155SupplyUpgradeable$Type } from "./ERC1155SupplyUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155SupplyUpgradeable"]: ERC1155SupplyUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/token/ERC1155/extensions/ERC1155SupplyUpgradeable.sol:ERC1155SupplyUpgradeable"]: ERC1155SupplyUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC1155SupplyUpgradeable"]: GetContractReturnType<ERC1155SupplyUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/token/ERC1155/extensions/ERC1155SupplyUpgradeable.sol:ERC1155SupplyUpgradeable"]: GetContractReturnType<ERC1155SupplyUpgradeable$Type["abi"]>;
  }
}
