// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ERC1155Utils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ERC1155Utils",
  "sourceName": "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Utils.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212206618905b3ce592db33969900d4face9764fa06c5b805502d999cd3eb00fe0a7764736f6c634300081c0033",
  "deployedBytecode": "0x5f80fdfea26469706673582212206618905b3ce592db33969900d4face9764fa06c5b805502d999cd3eb00fe0a7764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ERC1155Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC1155Utils$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Utils.sol:ERC1155Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC1155Utils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ERC1155Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC1155Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Utils.sol:ERC1155Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC1155Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ERC1155Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC1155Utils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Utils.sol:ERC1155Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC1155Utils$Type["abi"]>>;
}
