// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1155Upgradeable$Type } from "./ERC1155Upgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Upgradeable"]: ERC1155Upgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/token/ERC1155/ERC1155Upgradeable.sol:ERC1155Upgradeable"]: ERC1155Upgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC1155Upgradeable"]: GetContractReturnType<ERC1155Upgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/token/ERC1155/ERC1155Upgradeable.sol:ERC1155Upgradeable"]: GetContractReturnType<ERC1155Upgradeable$Type["abi"]>;
  }
}
