// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IJuryDAO$Type } from "./IJuryDAO";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IJuryDAO"]: IJuryDAO$Type;
    ["contracts/interfaces/IJuryDAO.sol:IJuryDAO"]: IJuryDAO$Type;
  }

  interface ContractTypesMap {
    ["IJuryDAO"]: GetContractReturnType<IJuryDAO$Type["abi"]>;
    ["contracts/interfaces/IJuryDAO.sol:IJuryDAO"]: GetContractReturnType<IJuryDAO$Type["abi"]>;
  }
}
