// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IJuryDAO$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IJuryDAO",
  "sourceName": "contracts/interfaces/IJuryDAO.sol",
  "abi": [
    {
      "inputs": [],
      "name": "jurorPoolSize",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "listingId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "buyer",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "seller",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "challenger",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "disputeFeeAmount",
          "type": "uint256"
        },
        {
          "internalType": "bytes32",
          "name": "evidenceHash",
          "type": "bytes32"
        },
        {
          "internalType": "string",
          "name": "evidenceURI",
          "type": "string"
        }
      ],
      "name": "openCase",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "caseId",
          "type": "uint256"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IJuryDAO",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IJuryDAO$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/IJuryDAO.sol:IJuryDAO",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IJuryDAO$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IJuryDAO",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IJuryDAO$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/IJuryDAO.sol:IJuryDAO",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IJuryDAO$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IJuryDAO",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IJuryDAO$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/IJuryDAO.sol:IJuryDAO",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IJuryDAO$Type["abi"]>>;
}
