// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PhygitalEscrow$Type } from "./PhygitalEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PhygitalEscrow"]: PhygitalEscrow$Type;
    ["contracts/PhygitalEscrow.sol:PhygitalEscrow"]: PhygitalEscrow$Type;
  }

  interface ContractTypesMap {
    ["PhygitalEscrow"]: GetContractReturnType<PhygitalEscrow$Type["abi"]>;
    ["contracts/PhygitalEscrow.sol:PhygitalEscrow"]: GetContractReturnType<PhygitalEscrow$Type["abi"]>;
  }
}
