// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MarketCollection$Type } from "./MarketCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarketCollection"]: MarketCollection$Type;
    ["contracts/MarketCollection.sol:MarketCollection"]: MarketCollection$Type;
  }

  interface ContractTypesMap {
    ["MarketCollection"]: GetContractReturnType<MarketCollection$Type["abi"]>;
    ["contracts/MarketCollection.sol:MarketCollection"]: GetContractReturnType<MarketCollection$Type["abi"]>;
  }
}
