// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ITrustToken$Type } from "./ITrustToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ITrustToken"]: ITrustToken$Type;
    ["contracts/interfaces/ITrustToken.sol:ITrustToken"]: ITrustToken$Type;
  }

  interface ContractTypesMap {
    ["ITrustToken"]: GetContractReturnType<ITrustToken$Type["abi"]>;
    ["contracts/interfaces/ITrustToken.sol:ITrustToken"]: GetContractReturnType<ITrustToken$Type["abi"]>;
  }
}
