// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SlotDerivation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SlotDerivation",
  "sourceName": "@openzeppelin/contracts/utils/SlotDerivation.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d694ca16e84734fc30ab863bcb96134ca3cd2fd9031dafce2e77f710459ab1ab64736f6c634300081c0033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220d694ca16e84734fc30ab863bcb96134ca3cd2fd9031dafce2e77f710459ab1ab64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
}
