// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMarketCollection$Type } from "./IMarketCollection";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMarketCollection"]: IMarketCollection$Type;
    ["contracts/interfaces/IMarketCollection.sol:IMarketCollection"]: IMarketCollection$Type;
  }

  interface ContractTypesMap {
    ["IMarketCollection"]: GetContractReturnType<IMarketCollection$Type["abi"]>;
    ["contracts/interfaces/IMarketCollection.sol:IMarketCollection"]: GetContractReturnType<IMarketCollection$Type["abi"]>;
  }
}
